### ISSUE TITLE
Jitpack support as AAR distribution

### ISSUE THREAD

**Issue by hamen** [AmniX/MaterialPatternllockView#1]
Hi
this https://jitpack.io/#AmniX/MaterialPatternllockView could work or you may need a setup like this one https://github.com/jitpack/gradle-simple

**Comment by AmniX** [comment]
Use it like follows 
     repositories {
         maven {
             url "https://jitpack.io"
         } 
     }
     dependencies {
         compile 'com.github.AmniX:MaterialPatternllockView:7a45dcaa79'
     }
